source 'http://rubygems.org'
gem 'sinatra', git: 'git@github.com:sinatra/sinatra.git'
gem 'pg'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'
gem 'pry'
gem 'dotenv'
gem 'json'
gem 'thin'
gem 'httparty'